export const userContants = {
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAIL: 'SIGN_UP_FAIL',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL'
}

export const productContants = {
    SIGN_IN : "SIGN_IN",
    SIGN_UP : "SIGN_UP",
    GET_OPERATIONS : "GET_OPERATIONS",
    DELETE_OPERATION : "DELETE_OPERATION",
    ADD_OPERATION : "ADD_OPERATION",
    UPDATE_OPERATION : "UPDATE_OPERATION",
    GET_OPERATION_BY_ID : "GET_OPERATION_BY_ID",
    FILTER_BY_TYPE : "FILTER_BY_TYPE",
}