export const GET_OPERATIONS = "GET_OPERATIONS";
export const DELETE_OPERATION = "DELETE_OPERATION";
export const ADD_OPERATION = "ADD_OPERATION";
export const UPDATE_OPERATION = "UPDATE_OPERATION";
export const GET_OPERATION_BY_ID = "GET_OPERATION_BY_ID";